deployments:
  - path: ../../../mxc-library/module/bases/namespaces
    tags: [infra, namespaces]

  - barrier: true

  - path: ../../../mxc-library/module/adapters/kluctl
    tags: [infra, traefik]
    vars:
      - values: {{ apps.infra.traefik | to_json }}
      - values:
          secrets:
            admin: {{ secrets.admin | default(secrets.infra.admin) | to_json }}

  - path: ../../../mxc-library/module/adapters/kluctl
    tags: [infra, metallb]
    vars:
      - values: {{ apps.infra.metallb | to_json }}

  - path: ../../../mxc-library/module/adapters/kluctl
    tags: [home, homarr]
    vars:
      - values: {{ apps.home.homarr | to_json }}
      - values:
          secrets:
            homarr: {{ secrets.homarr | to_json }}

  - path: ../../../mxc-library/module/adapters/kluctl
    tags: [media, silo]
    vars:
      - values: {{ apps.media.silo | to_json }}
